# Site settings
title: vourkosa
email: andreasvourkos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is my personal blog. I will regularly post here articles around monetization or android tricks. Opinions expressed here are of my own
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vourkosa.github.io" # the base hostname & protocol for your site
twitter_username: vourkosa
github_username:  vourkosa
gems:  
- jekyll-paginate
- jekyll-feed
paginate: 4
paginate_path: "page:num"
# Build settings
markdown: redcarpet
redcarpet:
    extension:
        - fenced_code_blocks
highlighter: pygments
comments:
    provider: disqus
disqus: 
    short_name: vourkosa
